# Generated by Django 5.1.5 on 2025-01-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('in_progress', 'Progress'), ('completed', 'Finalized')], default='sent', max_length=20),
        ),
    ]
